### ISSUE TITLE
"path must not be empty

### ISSUE THREAD

**Issue by paul-thompson-helix** [microsoft/parallel-prettier#13]
```
$ pprettier --check .
⠋ Starting........@mixer/parallel-prettier/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: path must not be empty
    at throwError (.....@mixer/parallel-prettier/node_modules/ignore/index.js:366:9)
    at checkPath (.....@mixer/parallel-prettier/node_modules/ignore/index.js:379:12)
    at Ignore._test (.....@mixer/parallel-prettier/node_modules/ignore/index.js:502:5)
    at Ignore.ignores (.....@mixer/parallel-prettier/node_modules/ignore/index.js:541:17)
    at Pumpify.<anonymous> (.....@mixer/parallel-prettier/dist/master.js:29:25)
    at Pumpify.emit (events.js:314:20)
    at addChunk (.....@mixer/parallel-prettier/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (.....@mixer/parallel-prettier/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Pumpify.Readable.push (.....@mixer/parallel-prettier/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at Pumpify.Duplexify._forward (.....@mixer/parallel-prettier/node_modules/duplexify/index.js:170:26)
```

**Comment by simkessy** [comment]
did you ever solve this, I have same issue

**Comment by martinnabhan** [comment]
Same issue here. This is super annoying as it forces you to specify filetype(s), while using . automatically only includes supported filetypes.
