### ISSUE TITLE
Prettier v3 support (and exceptions)

### ISSUE THREAD

**Issue by peterpeterparker** [microsoft/parallel-prettier#23]
Hi, I get following error when I try to use `pprettier` with Prettier v3:

```
Error: unknown type: "ChainExpression"
    at printPathNoParens (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:30038:17)
    at Object.genericPrint [as print] (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8550:22)
    at /Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8542:32
    at AstPath.call (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8359:24)
    at mainPrint (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8542:21)
    at printPathNoParens (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:29718:19)
    at Object.genericPrint [as print] (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8601:26)
```
    
and

```
Error: unknown node type: Script
    at Object.print (/Users/.../node_modules/prettier-plugin-svelte/plugin.js:1430:11)
    at callPluginPrintFunction (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8537:18)
    at AstPath.call (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8359:24)
    at printTopLevelParts (/Users/.../node_modules/prettier-plugin-svelte/plugin.js:1471:33)
    at Object.print (/Users/.../node_modules/prettier-plugin-svelte/plugin.js:892:16)
    at callPluginPrintFunction (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/.../node_modules/@mixer/parallel-prettier/node_modules/prettier/index.js:8537:18)
```

Do you plan to update the library to support v3?

## Reproduce the issue

```
git clone https://github.com/dfinity/nns-dapp
cd nns-dapp/frontend
git checkout build/prettier-v3
npm ci
npm run format
```

**Comment by dweitzman-codaio** [comment]
Looks like the codebase has support for prettier 3.0 now. Would it be possible to get an npm release?

**Comment by com6056** [comment]
@connor4312 any chance we can get a new NPM release soon? Thanks!

**Comment by arthurfiorette** [comment]
@tylerbutler

**Comment by ducle-infotrack** [comment]
Hi can anyone help release new npm?

**Comment by com6056** [comment]
@tylerbutler @connor4312 (or feel free to redirect me to whoever has the ability to) friendly bump on a new release here, thanks!

**Comment by RDIL** [comment]
Hi all, I published the current state of the master branch (with Prettier 3 support) to npm under [`@rdil/parallel-prettier`](https://npm.im/@rdil/parallel-prettier), feel free to use this, at least until the package is updated officially.

In your package.json:
```diff
- "@mixer/parallel-prettier": "^2",
+ "@rdil/parallel-prettier": "3.0.0",
```

I know, it's not a great solution, but it will work in the meantime. I'll mark it as deprecated once the upstream release is done.
